### ISSUE TITLE
gpiod version  (not working)

### ISSUE THREAD

**Issue by craigerl** [SirLefti/Python_ILI9486#3]
Sir, ... Lefti,

I ported the library to use gpiod instead of RPi.GPIO, however, I just can't get it to work, and was hoping you could take a look at it.  The screen doesn't reset or turn on.  The timing looks tricky for the reset too.  I'm not sure what gpiod introduces as far as lag goes.  Your RPi.GPIO version (with lgpio) works great, but we really need to move this, and everything over to libgpiod.

       https://craiger.org/craiger/ILI9486_gpiod.txt    (web server wont allow .py)

relevant portion of ILI9486_gpiod.py attached - thanks!
-craig

apt install python3-libgpiod

```

from enum import Enum
import time
import numpy as np
from PIL import Image, ImageDraw
#import RPi.GPIO as GPIO
import gpiod
from spidev import SpiDev

#GPIO.setmode(GPIO.BCM)



...



    def __init__(self, spi: SpiDev, dc: int, rst: int = None, *, origin: Origin = Origin.UPPER_LEFT):
        """Creates an instance of the display using the given SPI connection. Must provide the SPI driver and the GPIO
        pin number for the DC pin. Can optionally provide the GPIO pin number for the reset pin. Optionally the origin
        can be set. The default is UPPER_LEFT, which is landscape mode this the bottom of the image located at the
        power, video and audio out are of the Pi."""
        self.__spi = spi
        self.__dc = dc
        self.__rst = rst
        self.__origin = origin
        self.__width = LCD_WIDTH
        self.__height = LCD_HEIGHT
        self.__inverted = False
        self.__idle = False

#        GPIO.setmode(GPIO.BCM)
#        GPIO.setup(self.__dc, GPIO.OUT)
#        GPIO.output(self.__dc, GPIO.HIGH)
        chip = gpiod.Chip('gpiochip0')  # RPi always on 0  now.
        self.__dc_line = chip.get_line(self.__dc)
        self.__dc_line.request(consumer="dc", type=gpiod.LINE_REQ_DIR_OUT)
        self.__dc_line.set_value(1)

        if self.__rst is not None:
#            GPIO.setup(self.__rst, GPIO.OUT)
#            GPIO.output(self.__rst, GPIO.HIGH)
#             self.__rst_line = chip.get_line(self.__rst)
             self.__rst_line = chip.get_line(25)
             self.__rst_line.request(consumer="rst", type=gpiod.LINE_REQ_DIR_OUT)

        # swap width and height if selected origin is landscape mode by checking if third bit is 1
        if self.__origin.value & 0x20:
            self.__width, self.__height = self.__height, self.__width
        self.__buffer = Image.new('RGB', (self.__width, self.__height), (0, 0, 0))

    def dimensions(self) -> tuple:
        """Returns the current display dimensions"""
        return self.__width, self.__height

    def is_landscape(self) -> bool:
        """Returns true if selected origin is landscape mode; false otherwise"""
        return bool(self.__origin.value & 0x20)

    def send(self, data, is_data=True, chunk_size=4096):
        """Writes a byte or an array of bytes to the display."""
        # dc low for command, high for data
        #GPIO.output(self.__dc, is_data)
        self.__dc_line.set_value(1)

        if isinstance(data, int):
            self.__spi.writebytes([data])
        else:
            for start in range(0, len(data), chunk_size):
                end = min(start + chunk_size, len(data))
                self.__spi.writebytes(data[start: end])
        return self

    def command(self, data):
        """Writes a byte or an array of bytes to the display as a command."""
        return self.send(data, False)

    def data(self, data):
        """Writes a byte or an array of bytes to the display as data."""
        return self.send(data, True)

    def reset(self):
        """Resets the display if a reset pin is provided."""
        if self.__rst is not None:
            #GPIO.output(self.__rst, GPIO.HIGH)
            self.__rst_line.set_value(1)
            time.sleep(.001)  # wait a bit to make sure the output was HIGH
            #GPIO.output(self.__rst, GPIO.LOW)
            self.__rst_line.set_value(0)
            time.sleep(.000100)  # wait 100 µs to trigger the reset (should be 10 µs, but the OS is not precise enough)
            #GPIO.output(self.__rst, GPIO.HIGH)
            self.__rst_line.set_value(1)
            time.sleep(.120)  # wait 120 ms for finishing blanking and resetting
            self.__inverted = False
            self.__idle = False
            return self


```

**Comment by SirLefti** [comment]
Hi, I created a `libgpiod` branch with a quick and dirty rewrite with said library. Try this instead.

It seems that your attached code uses `gpiod` in version `1.x`. When I installed the lib in the latest `2.x` version and played around with it, there was no `get_line` function. So I did it a bit different, but it works for me an my older py.

I will probably make it co-exist for a while. I am not fully commited to change the underlying lib, as long as `rpi-lgpio` is sufficient for the job.

What are your reasons to change? 
For the next time, please also consider forking the repo and pushing your changes to your fork. This makes it much easier to just clone your changes and eliminates the need of an external server to host the patches.

**Comment by craigerl** [comment]
Thanks for looking!

I'm going with  mainstream version of libgpiod for Raspberry Pi OS bookworm, which, as I type, appears to be 1.6.3?
python3-libgpiod/stable,now 1.6.3-1+rpi1+b2 armhf [installed]
  Python bindings for libgpiod (Python 3)

Why gpiod?  everything is moving to that and the kernel character devices for gpio.   lgpio is a compatibility later for the now-obsolete (and removed) RPi.GPIO /sys interface.  It's a hassle, but I'm porting all my gpio stuff, and I'm using your brilliant ILI9486 library.

https://craiger.org/direwatch.png

I'll take a look at the branch thanks, and yes, if i had something working, I'd do a pull request.

thanks,
-craig

**Comment by craigerl** [comment]
I think this is expected on python3-libgpiod 1.6.3,  ?

```
$ ./image.py 
Traceback (most recent call last):
  File "/home/pi/git/Python_ILI9486/./image.py", line 6, in <module>
    import ILI9486 as LCD
  File "/home/pi/git/Python_ILI9486/ILI9486.py", line 26, in <module>
    from gpiod.line import Direction, Value
ModuleNotFoundError: No module named 'gpiod.line'; 'gpiod' is not a package
```

**Comment by SirLefti** [comment]
Most likely. I am working in virtual environments anyways, so I went the `pip install gpiod` way instead of `apt install python3-libgpiod`, which gives me the latest version. 

I might take a look at `1.x` as well. But at some point, bookworm or its successors will also switch to `2.x`. So maybe it is worth to consider for you migrating to that version now, when you are already in the process of migrating from another lib.

Can you provide an error you got with your migration code in `1.x`?

**Comment by SirLefti** [comment]
Ok, you can take a look at the `libgpiod-legacy` branch, which is basically more or less like the code you provided. Works fine for me. The issue is probably on your device, or something that is interfering with it.

**Comment by craigerl** [comment]
thanks for the legacy - it goes through reset/on/off, etc, however when drawing the sample.png it's as if the origin shifts each time, so the image isn't centered in the screen.   each loop the origin moves to the left about 20 pixels.   I know I'm not explaining this very well.  I saw this before during other tests.

**Comment by craigerl** [comment]
I take that back, had wrong gpiochip selected - it works perfectly!  thanks again
